# 1. What are data structures, and why are they important
WAY OF ORGANIZING AND STORING DATA SO THAT IT CAN BE ACCESSED AND MANIPULATED EFFECIENTLY STRING , LISTS, SET , TUPLES,ARRAY , DICTIONARY .

# 2. Explain the difference between mutable and immutable data types with examples
 ***MUTABLE*** :-
  IT CAN BE CHANGED AFTER CREATION .
  EX - LIST , DICTIONARY , SET
***  IMMUTABLE*** :-
IT CANNOT BE CHANGED AFTER CREATION .
EX - INT , STRING , TUPLE

# 3.  What are the main differences between lists and tuples in Python
***`LIST `***
> IT IS MUTABLE
> IT IS SLOWER
> IT CAN USED TO CHANGE DATA
> SYNTX - [ 1 , 2 , 3 ]
***`TUPLE `***
> IT IS IMMUTABLE
> IT IS FASTER
> IT CAN USED TO FIX DATA
> SYNTX - ( 1 , 2 , 3 )

# 4. Describe how dictionaries store data
IT STORE DATA IN KEY VALUE PAIRS

# 5. Why might you use a set instead of a list in Python
Sets are useful when you need to store a collection of unique elements or perform mathematical set operations like union, intersection, and difference. Lists, on the other hand, can store duplicate elements and are ordered.

# 6.  What is a string in Python, and how is it different from a list
STRING IS A SEQUENCE OF CHARACTERS , IT IS IMMUTABLE .
LIST IS A SEQUENCE OF ELEMENTS , IT IS MUTABLE

# 7.  How do tuples ensure data integrity in Python
TI IS IMMUTABLE SO ONCE CREATED THEIR DATA CANNOT BE CHANGED , MAKING THEM RELIABLE FOR FIXED DATA .

# 8. What is a hash table, and how does it relate to dictionaries in Python

# 9. Can lists contain different data types in Python
YES  lists contain different data types in Python

# 10 . Explain why strings are immutable in Python
FOR MEMORY EFFICIENCY

# 11.What advantages do dictionaries offer over lists for certain tasks
FAST ACCESS BY KEY
BETTER STRUCTURE FOR LABELED DATA

# 12.Describe a scenario where using a tuple would be preferable over a list
STORING CONSTANT DATA LIKE COORDINATES

# 13.  How do sets handle duplicate values in Python
AUTOMATICALLY

# 14. How does the “in” keyword work differently for lists and dictionaries
***LIST - ***CHECKS FOR VALUE
***DICTIONARY -*** CHECKS FOR KEYS

# 15 . Can you modify the elements of a tuple? Explain why or why not
NO WE CANNOT modify the elements of a tuple , BECZ IT IS IMMUTABLE

# 16. What is a nested dictionary, and give an example of its use case
A DICTIONARY INSIDE ANOTHER DICTIONARY


```
# STUDENT = { 'NAME' : 'CHARCHIT', 'MARKS' : { 'MATH' : 90 , 'SCIENCE' : 80 }}
```

# 17. Describe the time complexity of accessing elements in a dictionary
AVERAGE

# 18. In what situations are lists preferred over dictionaries
WHEN ELEMENTS DONT NEED UNIQUE KEYS

# 19. Why are dictionaries considered unordered, and how does that affect data retrieval
THEY DON'T PRESERVE INSERTION OEDER (BEFORE PY -3.7)

# 20. P Explain the difference between a list and a dictionary in terms of data retrieval
LIST - BY INDEX
DICTIONARY - BY KEY

**" PRACTICAL QUESTIONS " **

In [ ]:
# 1.  Write a code to create a string with your name and print it
NAME ="CHARCHIT JAIN"
print(NAME)

CHARCHIT JAIN

In [ ]:
# 2.Write a code to find the length of the string "Hello World"
print(len("hello world"))

11

In [ ]:
# 3. Write a code to slice the first 3 characters from the string "Python Programming"
print("python programming"[0:3])

pyt

In [ ]:
# 4. Write a code to convert the string "hello" to uppercase
print("hello".upper())

HELLO

In [ ]:
# 5. Write a code to replace the word "apple" with "orange" in the string "I like apple"
print("I like banana ".replace("banana","appricot"))

I like appricot

In [ ]:
# 6. Write a code to create a list with numbers 1 to 5 and print it
print(list(range(1,6)))

[1, 2, 3, 4, 5]

In [ ]:
# 7.Write a code to append the number 10 to the list [1, 2, 3, 4]
lst=[1 , 2 , 3 , 4]
lst.append(3455)
print(lst)

[1, 2, 3, 4, 3455]

In [ ]:
# 8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
lst =[1,2,3,4,5]
lst.remove(3)
print(lst)

[1, 2, 4, 5]

In [ ]:
#9.Write a code to access the second element in the list ['a', 'b', 'c', 'd']
letters =['a','b','c','d']
print(letters[1])

b

In [ ]:
# 10.  Write a code to reverse the list [10, 20, 30, 40, 50]
lst =[10, 20, 30, 40, 50]
print(lst)

[10, 20, 30, 40, 50]

In [ ]:
# 11. Write a code to create a tuple with the elements 100, 200, 300 and print it
t= (100 ,200 ,300)
print(t)

(100, 200, 300)

In [ ]:
# 12.  Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')
colors = ('red', 'green', 'blue', 'yellow')
print(colors[-2])

blue

In [ ]:
# 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15)
print(min((10, 20, 5, 15)))

5

In [ ]:
# 14.Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

animals= ('dog', 'cat', 'rabbit')
print(animals.index("cat"))

1

In [ ]:
# 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it
fruits=('apple', 'kele','santra')
print("angur" in fruits)

False

In [ ]:
#16. Write a code to create a set with the elements 'a', 'b', 'c' and print it
s= {'a', 'b','c'}
print(s)

{'c', 'b', 'a'}

In [ ]:
#17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}
s={1, 2, 3, 4, 5}
s.clear()
print(s)

set()

In [ ]:
#18.  Write a code to remove the element 4 from the set {1, 2, 3, 4}
s={1, 2, 3, 4}
s.remove(4)
print(s)

{1, 2, 3}

In [ ]:
#19 Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}
print({1,2,3} | {3,4,5})

{1, 2, 3, 4, 5}

In [1]:
#20  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}
print({1,2,3} & {2,3,4})

{2, 3}

In [2]:
#21 Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
d= {'name': 'charchit jain', 'age': 20, 'city': 'binauli'}
print (d)

{'name': 'charchit jain', 'age': 20, 'city': 'binauli'}

In [3]:
#22 Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
d={'name': 'John', 'age': 25}
d['country']="USA"
print(d)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [4]:
#23 Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
d={'name': 'Alice', 'age': 30}
print(d['name'])

Alice

In [5]:
#24  Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}
d={'name': 'Bob', 'age': 22, 'city': 'New York'}
del d['age']
print(d)

{'name': 'Bob', 'city': 'New York'}

In [6]:
#25 Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}
d={'name': 'Alice', 'city': 'Paris'}
print('city' in d)

True

In [7]:
#26  Write a code to create a list, a tuple, and a dictionary, and print them all.
l=[1 ,2]; t=(1,2); d={1:2}
print(l,t,d)

[1, 2] (1, 2) {1: 2}

In [9]:
#27  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
# result.(replaced)
import random
nums=random.sample(range(1,101),5)
nums.sort()
print(nums)

[2, 4, 55, 67, 86]

In [10]:
#28  Write a code to create a list with strings and print the element at the third index
lst=['jiya ','siya','miya','riya','sofaiya']
print(lst[3])

riya

In [11]:
#29 Write a code to combine two dictionaries into one and print the result.
d1={'a':1,'b':2}
d2={'c':3,'d':4}
print({**d1,**d2})

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [12]:
# 30 Write a code to convert a list of strings into a set.
lst=['  i','love','you','jiya']
print(set(lst))

{'jiya', '  i', 'you', 'love'}